app:
  mongodb:
    uri: ${MONGODB_URI:}
  mail:
    no-reply: "no-reply@pes5.com"
    title: "ASL Soccer 5"
    sendgrid:
      url: "https://api.sendgrid.com/v3"
      api-key: ${SENDGRID_API_KEY:}
server:
  port: ${PORT:8080}
