name: Docker

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      env:
        USERNAME: ${{ secrets.USERNAME }}    
        TOKEN: ${{ secrets.TOKEN }}    
      run: | 
        docker build -t docker.pkg.github.com/binout/soccer-league/app:latest .
        docker login -u ${USERNAME} -p ${TOKEN}
        docker push docker.pkg.github.com/binout/soccer-league/app:latest

